### ISSUE TITLE
Why On Android version 9 Toast doesn't showing. Please checking

### ISSUE THREAD

**Issue by Theeranail** [Spikeysanju/MotionToast#20]
on android 9 doesn't showing but trying on android 7,8,10,11 is no problem

**Comment by Spikeysanju** [comment]
1. Kindly re-check if you turned off the `notification` for your app.
2. `Restart` your device & check if it works

**Comment by Theeranail** [comment]
i try to do follow you. But is doesn't work.
devices ->  Xiaomi Mi 9T Android version 9

**Comment by david-serrano** [comment]
@Theeranail i found the solution to this, essentially, the issue is that the view was getting re-added unnecessarily on each timer tick, so for whatever toast you're using, if you clone the repository, you can make it work by deleting the `toast.show()` method inside each `onTick` callback for the timers in the MotionToast versions you're using. I will try to submit a PR that fixes this soon - this lib is very cool, but could use some improvements for customisations imo 😄

**Comment by Spikeysanju** [comment]
@Theeranail Thanks, man!. It will be great if you just make PR for this issue 👍

**Comment by Theeranail** [comment]
Thanks. @Spikeysanju @david-serrano
